raytracer: raytrace.cpp
	g++ -o raytrace raytrace.cpp -O2 --std=c++1y -Wall -Wextra && ./raytrace && "C:\Program Files\IrfanView\i_view64.exe" image.ppm

view:
	"C:\Program Files\IrfanView\i_view64.exe" image.ppm